/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1estructuras;

import javax.swing.JOptionPane;

/**
 *
 * @author jmmor
 */
public class Juego extends javax.swing.JFrame {

    boolean bandera;

    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBandera = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        casilla = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicio.setText("Volver a Inicio");
        jPanel1.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 13, 160, 50));

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        btnBandera.setText("Bandera");
        btnBandera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanderaActionPerformed(evt);
            }
        });
        jPanel1.add(btnBandera, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 140, -1));

        btnGuardar.setText("Guardar juego");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 170, -1));

        casilla.setText("A1");
        casilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casillaActionPerformed(evt);
            }
        });
        jPanel1.add(casilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 770, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void casillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casillaActionPerformed
        /*
        
        Asumiendo que los nodos contienen una variable de si es o no una bomba
        
        Nodo :
            boolean es_bomba
            int bombas_ady  --> O la variable/funcion que determine la cantidad de bombas adyacentes a un nodo
        
        */
        
//        Nodo casilla = grafo.buscar(this.jToggleButton1.getText());
        if(this.casilla.isSelected()){
            if(this.casilla.getText().equals("BANDERA") && this.bandera == false){
                return;
            }
            if(bandera){
                if(this.casilla.getIcon().equals("bandera")){
                    this.casilla.setIcon(null);
                }else{
//                this.jToggleButton1.setIcon(bandera);
                this.casilla.setText("BANDERA");}
            } else {
                if(casilla.es_bomba){
                    JOptionPane.showInputDialog("Perdistes");
                } else {
                    if (casilla.bombas_ady == 0){
//                        this.barrido
                    } else{
//                        this.jToggleButton1.setText(casilla.bombas_ady);
                    
                    
                    }
                    
                    
                
                }

            this.casilla.setEnabled(false);
            }
        }
    }//GEN-LAST:event_casillaActionPerformed

    private void btnBanderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanderaActionPerformed
        if (bandera) {
            bandera = false;
        } else {
            bandera = true;
        }
    }//GEN-LAST:event_btnBanderaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBandera;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JToggleButton casilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
