/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author jmmor
 */
public class CargarPartida extends javax.swing.JFrame {
    
    private int nroFilas, nroColumnas, nroMinas;
  
    public CargarPartida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Partida1 = new javax.swing.JButton();
        Partida3 = new javax.swing.JButton();
        Partida2 = new javax.swing.JButton();
        VolverInicio = new javax.swing.JButton();
        GuardarPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 36)); // NOI18N
        jLabel1.setText("Cargar Partida");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Partida1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        Partida1.setText("Partida 1");
        Partida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Partida1ActionPerformed(evt);
            }
        });
        jPanel1.add(Partida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 170, -1));

        Partida3.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        Partida3.setText("Partida 3");
        Partida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Partida3ActionPerformed(evt);
            }
        });
        jPanel1.add(Partida3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, -1));

        Partida2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        Partida2.setText("Partida 2");
        Partida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Partida2ActionPerformed(evt);
            }
        });
        jPanel1.add(Partida2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 170, -1));

        VolverInicio.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        VolverInicio.setText("Volver a Inicio");
        VolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverInicioActionPerformed(evt);
            }
        });
        jPanel1.add(VolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        GuardarPartida.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        GuardarPartida.setText("Guardar Partida");
        GuardarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverInicioActionPerformed
        BuscaminasInterfaz regreso = new BuscaminasInterfaz();
        regreso.setVisible(true);
        regreso.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_VolverInicioActionPerformed

    private void GuardarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarPartidaActionPerformed
        
    }//GEN-LAST:event_GuardarPartidaActionPerformed

    private void Partida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Partida3ActionPerformed
        Juego jugarGuardado = new Juego(nroFilas, nroColumnas, nroMinas);
        jugarGuardado.setVisible(true);
        jugarGuardado.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_Partida3ActionPerformed

    private void Partida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Partida1ActionPerformed
        Juego jugarGuardado = new Juego(nroFilas, nroColumnas, nroMinas);
        jugarGuardado.setVisible(true);
        jugarGuardado.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Partida1ActionPerformed

    private void Partida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Partida2ActionPerformed
        Juego jugarGuardado = new Juego(nroFilas, nroColumnas, nroMinas);
        jugarGuardado.setVisible(true);
        jugarGuardado.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_Partida2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargarPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarPartida;
    private javax.swing.JButton Partida1;
    private javax.swing.JButton Partida2;
    private javax.swing.JButton Partida3;
    private javax.swing.JButton VolverInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
